### PR TITLE
Erddap

### PR DESCRIPTION
**Pull request by ocefpaf**
New notebook demonstrating the `ERDDAP ` server behind the the IOOS Sensor Map:

Hypothes.is for review: https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/ERDDAP/notebooks/2017-03-21-ERDDAP_IOOS_Sensor_Map.ipynb

This one is ready for review @jbosch-noaa.

### CODE REVIEW

**Comment by jbosch-noaa** [comment]
Thanks @ocefpaf. I will take a look at it but I would love for @kbailey-noaa and Tiffany.C.Vance@noaa.gov to review this notebook as well. :)

**Comment by jbosch-noaa** [comment]
@ocefpaf - Is there a reason why you chose a George's Bank buoy? I'm trying to create a use story in the comments of the notebook.

**Comment by ocefpaf** [comment]
> @ocefpaf - Is there a reason why you chose a George's Bank buoy? I'm trying to create a use story in the comments of the notebook.

No special reason besides that is a buoy that I known :smile:

**Comment by jbosch-noaa** [comment]
Ok @ocefpaf  - I'm done making comments in hypothes.is

**Comment by ocefpaf** [comment]
Thanks @jbosch-noaa! Applying the suggestions now. Will ping you once I'm done.

**Comment by ocefpaf** [comment]
@jbosch-noaa I applied all your review comments here and made a few comments on `hypothes.is` regarding your questions/comments. This is ready for a second parse!

**Comment by rsignell-usgs** [comment]
I made some more comments on 
https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/ERDDAP/notebooks/2017-03-21-ERDDAP_IOOS_Sensor_Map.ipynb

**Comment by ocefpaf** [comment]
> I made some more comments on
https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/ERDDAP/notebooks/2017-03-21-ERDDAP_IOOS_Sensor_Map.ipynb

Implementing them in my next commit... Hold on...

**Comment by jbosch-noaa** [comment]
@rsignell-usgs  - I commented on your comment.  Thanks for your input. :)

**Comment by rsignell-usgs** [comment]
Okay, I should have done wave height instead of sea surface temperature, but what do you think about the overall idea?     Here are wave height snapshots instead:

**Comment by rsignell-usgs** [comment]
http://erddap.axiomdatascience.com/erddap/tabledap/sensor_service.csvp?time%2Cdepth%2Cstation%2Cparameter%2Cunit%2Cvalue&time%3E=2017-02-27T12%3A00%3A00Z&station=%22urn%3Aioos%3Astation%3Awmo%3A44011%22&parameter=%22Significant%20Wave%20Height%22&unit=%22m%22

**Comment by ocefpaf** [comment]
@rsignell-usgs to make your point that the URL is easily readable we need to unquote it first :wink: 

```python
from urllib.parse import unquote

url = 'http://erddap.axiomdatascience.com/erddap/tabledap/sensor_service.csvp?time%2Cdepth%2Cstation%2Cparameter%2Cunit%2Cvalue&time%3E=2017-02-27T12%3A00%3A00Z&station=%22urn%3Aioos%3Astation%3Awmo%3A44011%22&parameter=%22Significant%20Wave%20Height%22&unit=%22m%22'
unquote(url)
'http://erddap.axiomdatascience.com/erddap/tabledap/sensor_service.csvp?time,depth,station,parameter,unit,value&time>=2017-02-27T12:00:00Z&station="urn:ioos:station:wmo:44011"&parameter="Significant Wave Height"&unit="m"'
```

**Comment by ocefpaf** [comment]
I implemented @rsignell-usgs' suggestions in https://github.com/ioos/notebooks_demos/pull/198/commits/5a18cf853d3fc156906782a7c796d818d2236e14 this is ready for another round of reviews :grimacing:

**Comment by rsignell-usgs** [comment]
@ocefpaf, cool!  I did not know about `unquote(url)`

**Pull request merged**
