### PR TITLE
Finish SIPHON_NCSS_HFR_DataAccess

### PR DESCRIPTION
**Pull request by ocefpaf**
Start to address #4

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jbosch-noaa and @rsignell-usgs let me know if you have any feedback before we merge this notebook.

http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/SIPHON_NCSS_HFR_DataAccess/notebooks/hfradar/SIPHON_NCSS_HFR_DataAccess.ipynb

**Comment by rsignell-usgs** [comment]
I would add a static plot at a specified time step in a cell  before the animation cell.  
- plot at one time step
- "now let's animate!"

**Comment by ocefpaf** [comment]
> I would add a static plot at a specified time step in a cell before the animation cell.

Done!

**Comment by rsignell-usgs** [comment]
Woo hoo!  Great improvement Filipe!

**Pull request merged**
