### PR TITLE
erddapy

### PR DESCRIPTION
**Pull request by ocefpaf**
# ~~Not ready for review!~~

This notebook demonstrate the Python ERDDAP URL constructor. `erddapy`'s goal is to make it easier to obtain endpoints that can be used by `pandas`, `xarray`, or any other tool that reads ERDDAP's many formats.

### CODE REVIEW

**Comment by ocefpaf** [comment]
This one is ready for review @jbosch-noaa 

https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/erddapy/notebooks/2018-03-01-erddapy.ipynb

Ping @rsignell-usgs whose scripts had an important part in the creation of `erddapy` and is also an author of that package.

**Comment by jbosch-noaa** [comment]
Ok @ocefpaf  - I made some polishing comments. :)

**Comment by ocefpaf** [comment]
> Ok @ocefpaf - I made some polishing comments. :)

Done! Ready for another round.

**Comment by jbosch-noaa** [comment]
Flagged a few minor tweaks .

**Comment by ocefpaf** [comment]
> Flagged a few minor tweaks.

Thanks @jbosch-noaa! I think I got them all.

**Pull request merged**
