### PR TITLE
Matlab/Octave demo

### PR DESCRIPTION
**Pull request by ocefpaf**
This is a very simple `Matlab`/`Octave` notebook demostration.

I did want to make this a copy of https://github.com/ioos/notebooks_demos/pull/201 using `Matlab` instead of `R`. However, I am limited to running only code that is compatible with `Octave`, because `Matlab` is non-free. Unfortunately `xtractomatic` is not compatible with `octave` (nor even old versions of Matlab).

Note that I don't use Matlab for more than 10 years now and I am unaware of interesting toolboxes that users might want to see. Please ping me with suggestions!

Here is the `hypothes.is` link: https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/matlab_octave/notebooks/2017-03-30-octave_notebook_example.ipynb?flush_cache=true

### CODE REVIEW

**Comment by jbosch-noaa** [comment]
Thanks for taking a stab at this @ocefpaf .  Actually, I think @mbiddle-ndoc might have some good input here.  
Matt - What do you think?  Do you have a good IOOS data / oceanographic matlab example?

**Comment by ocefpaf** [comment]
@jbosch-noaa I also fixed a number of CI failures in this PR. Let me know if you are OK with this Matlab/Octave notebook example. If not I will pull the commits from the CI fixes into another PR so safe them.

**Comment by jbosch-noaa** [comment]
I looked over this notebook and I think it looks good.  This is an appropriate first notebook for Matlab.  It sets the stage for more Matlab notebooks in the future. :)

**Comment by jbosch-noaa** [comment]
Oh no!  I just saw that this notebook doesn't have a title on the thumbnail!!  @ocefpaf - would you please fix that. Perhaps title it "Simple Matlab/Octave Demo"

**Comment by ocefpaf** [comment]
I'll fix this later today. (Got stuck in Atlanta last night due to weather
and I did not make it to Boston yet.)

**Pull request merged**
