### PR TITLE
Added jupyter{book} for IOOS website

### PR DESCRIPTION
**Pull request by lohithmunakala**
This PR is in response to the issue https://github.com/ioos/notebooks_demos/issues/386 which was to **create a jupyterbook style website for all the notebooks present** on IOOS Data Demo Center.  

I have created a base jupyter{book} which consist of all the files required to run a jupyterbook on Github pages. As of now, I have only added 2 notebooks and would like to know how we can classify the notebooks into different chapters and subchapters. 

**@ocefpaf and @MathewBiddle  could you please help me out with the addition of the rest of the notebooks to their respective chapters/folders ?** 

**All the files have been added to the folder "jupyterbook".**

Here are a few screenshots of the jupyter{book} website and the design.

## 1. Homepage
 Screenshot from 2021-03-11 18-50-21

## 2. Other Resources Installation Page 
 Screenshot from 2021-03-11 18-50-29

## 3. A preview of a Notebook 
Screenshot from 2021-03-11 18-50-41

### CODE REVIEW

**Comment by lohithmunakala** [comment]
After the initial making of the book, I have added all the other notebooks to the jupyter{book} expect for the R Notebooks. 

I have divided the classes into 3 types:

- Data Collection
- Data Analysis
- Data PreProcessing 

The Data Preprocessing subheading/chapter names have a bit of an issue which can be solved at a later stage. 
## 1. The updated website looks like this now:

Screenshot from 2021-03-14 03-34-54

## 2. Notebooks in the Data Collection Chapter 
Screenshot from 2021-03-14 03-51-17


## 3. Notebooks in the Data Analysis Chapter 
Screenshot from 2021-03-14 03-51-13


## 4. Notebooks in the Data Preprocessing Chapter 


Screenshot from 2021-03-14 03-49-07


## 5. A View of the Plot Generated by one of the Notebooks
Screenshot from 2021-03-14 03-35-57

**Comment by ocefpaf** [comment]
@MathewBiddle I don't recall the sections we decided in our last meeting (I believe that Tiffany had a really nice idea), did you take notes? I guess they were along the lines of:

- Data Access
- Data Analysis and Visualization
- Standards and Metadata (Data Publication?)

**Comment by MathewBiddle** [comment]
@ocefpaf, yes those were the sections we discussed. Something like find data, use data, and manage data.

**Comment by lohithmunakala** [comment]
> @ocefpaf, yes those were the sections we discussed. Something like find data, use data, and manage data.

So @ocefpaf @MathewBiddle  should I rename the chapters to the following?

- Data Access
- Data Analysis and Visualization
- Data Publication 

Also, can you help me with regards to which folder the notebooks should be placed in? I have placed them based on how I have understood the notebooks. 

Thanks!

**Comment by ocefpaf** [comment]
> So @ocefpaf @MathewBiddle should I rename the chapters to the following?

Sure. But let's convert this PR to a draft for now as this would probably be part of your GSoC application, correct?

**Comment by lohithmunakala** [comment]
> > So @ocefpaf @MathewBiddle should I rename the chapters to the following?
> 
> Sure. But let's convert this PR to a draft for now as this would probably be part of your GSoC application, correct?

Yes, it would be a part of my GSoC application although I don't mind merging the PR if it is fine enough. I have some changes to make and the issue with the R notebooks not having the kernel isn't sorted out yet.

**Comment by lohithmunakala** [comment]
@ocefpaf @MathewBiddle can I know if there is any requirements.txt file for all the notebooks> It would be easy to build the notebooks. Thanks!

**Comment by lohithmunakala** [comment]
> > @ocefpaf, yes those were the sections we discussed. Something like find data, use data, and manage data.
> 
> So @ocefpaf @MathewBiddle should I rename the chapters to the following?
> 
>     * Data Access
> 
>     * Data Analysis and Visualization
> 
>     * Data Publication
> 
> 
> Also, can you help me with regards to which folder the notebooks should be placed in? I have placed them based on how I have understood the notebooks.
> 
> Thanks!

@ocefpaf @MathewBiddle I have renamed the folders to the above-mentioned chapters. 
Screenshot from 2021-03-23 18-02-03

Can you help me out with the **R Kernel Issue**? It doesn't let jupyter build the book. And there are around 5 notebooks which are in R and Matlab.

**Comment by ocefpaf** [comment]
> @ocefpaf @MathewBiddle, there is an issue that has come up with regards to the libraries that are being used in the notebooks. The two libraries causing issues are:
> 
> ```
> 1. compliance_checker
> 2. cf-untis 
> ```
> 
> Both of the libraries give the error **#include "udunits2.h" no such file or directory**. I guess compliance_checker is using cf-units hence the same error.
> 
> I have googled about these and they seem to be have been made by the IOOS folks themselves. How can I get through this?

How are you installing them? With conda you should not worry about that. There is a section in our page on how to use conda here: https://ioos.github.io/notebooks_demos/other_resources/

Let me know if that helps.

**Comment by lohithmunakala** [comment]
> > @ocefpaf @MathewBiddle, there is an issue that has come up with regards to the libraries that are being used in the notebooks. The two libraries causing issues are:
> > ```
> > 1. compliance_checker
> > 2. cf-untis 
> > ```
> > 
> > 
> > Both of the libraries give the error **#include "udunits2.h" no such file or directory**. I guess compliance_checker is using cf-units hence the same error.
> > I have googled about these and they seem to be have been made by the IOOS folks themselves. How can I get through this?
> 
> How are you installing them? With conda you should not worry about that. There is a section in our page on how to use conda here: https://ioos.github.io/notebooks_demos/other_resources/
> 
> Let me know if that helps.

I was trying to still them using pip. Will use conda to get the installation done. Thanks for the help!

**Comment by ocefpaf** [comment]
> I was trying to install them using pip. Will use conda to get the installation done. Thanks for the help!

A lot of packages in the scientific world are not pip installable. We require a full-fledged package managers instead.

**Comment by lohithmunakala** [comment]
- Adding the R, Matlab notebooks to the jupyter{book}. Solved the issue where the kernel was not being detected. 
# Here are some samples 
## Basic Home Screen / Landing Page for R and Matlab Notebooks
Screenshot from 2021-04-01 04-48-16
## A Matlab Notebook Primer (Matlab Demo)
Screenshot from 2021-04-01 04-59-09
## Calling R from Python Notebook (R Demo)
Screenshot from 2021-04-01 04-58-57

Any more suggestions would be helpful @ocefpaf @MathewBiddle. 

Thanks a ton!

**Comment by ocefpaf** [comment]
Hi @lohithmunakala are you available for a call to touch base on these details?

**Comment by lohithmunakala** [comment]
> Hi @lohithmunakala are you available for a call to touch base on these details?

Hey @ocefpaf ! When can we have the call?

**Comment by ocefpaf** [comment]
@lohithmunakala conflicts with notebooks are quite hard to solve correctly. Do you mind re-issuing your PR? It would also be nice so we can take an iterative approach. Sent a PR with as little change as possible to get the basic JB working and we will go from there.

**Comment by lohithmunakala** [comment]
Sure. I'll reissue a PR. Probably will make the issues go away,

**Pull request closed without merging**
