### PR TITLE
Add IOOS_data_demo

### LINKED ISSUE #51: Simple CSW search example
Add a notebook with a simple CSW query that can be easily adapted to any region.

### PR DESCRIPTION
**Pull request by ocefpaf**
# This notebook is not ready yet! Do not merge!!

I am adapting http://nbviewer.jupyter.org/github/ocefpaf/sscsw/blob/master/IOOS_data_demo.ipynb to use https://dev-catalog.ioos.us/csw instead of NGDC but I am failing to find SOS endpoints for the data.

@emiliom and @rsignell-usgs any advice?

Closes #51

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Filipe, I don't know, but SOS search seems to be working fine here:
http://nbviewer.jupyter.org/gist/rsignell-usgs/e3f10e28a805c9316049e4ceb8c838ae
see first 12 cells.

**Comment by ocefpaf** [comment]
> Filipe, I don't know, but SOS search seems to be working fine here

Thanks. I will take a closer look later next week.

**Comment by emiliom** [comment]
I don't have anything to add to @rsignell-usgs's comments and notebook (nice notebook). I haven't tested running service requests against https://dev-catalog.ioos.us/csw yet.

Tangentially, regarding Rich's finding/comment below cell 3 of his notebook:

> Hmmm..... In the query above, we only get 10 records, even though we specified `maxrecords=100`.
> What's up with that?
> Turns out the CSW service specified a `MaxRecordDefault` that cannot be exceeded. 

That `MaxRecordDefault` setting seems overly aggressive and not very helpful to clients. I'd ping Micah to have it relaxed. That'd be a timely suggestion, given [Micah's email from Friday about the new IOOS Catalog](https://groups.google.com/d/msg/ioos_tech/QxNUXpMeegk/oNd7k_ARAQAJ). (BTW, @ocefpaf, I assume you're on the `ioos_tech` list?)

**Comment by ocefpaf** [comment]
Closing this for now because a lot has changed in the underline page creation. I will re add this PR later.

**Pull request closed without merging**
