### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by MathewBiddle**
adding google analytics measurement ID

closes https://github.com/ioos/notebooks_demos/issues/190

### CODE REVIEW

**Comment by MathewBiddle** [comment]
@ocefpaf and @mwengren, I've poked around and think this is all we need to do to get tracking setup. If that is not correct, please point me to the appropriate documentation and I can make whatever other changes are necessary.

**Review by mwengren — APPROVED** [review]
Hey @MathewBiddle, looks reasonable to me.  Did you run it locally and see a JS script included somewhere in the rendered HTML with the ID?  That should be all that's necessary from the template side to make it work - hopefully GA will work on the other end.

**Comment by MathewBiddle** [comment]
@mwengren good call. I'll spin it up locally and see what I find.

**Comment by MathewBiddle** [comment]
@mwengren No clue if this is right but after deploying locally I see this javascript piece with that identifier in it:
image

FWIW, I've documented what I did to run the website locally in [this wiki page](https://github.com/ioos/notebooks_demos/wiki/Deploying-demo-center-website-on-your-local-machine).

**Comment by mwengren** [comment]
Looks promising.  I'm not sure how GA works exactly - I doubt you'll be able to see any metrics on the dashboard because it's running on your localhost in dev mode.  You'll probably have to deploy to the ioos.github.io URL to know if it actually works or not.

**Comment by MathewBiddle** [comment]
@ocefpaf I'll let you take a look and see if I broke anything before we merge.

**Comment by ocefpaf** [comment]
That should do it. Let's merge it!

**Comment by MathewBiddle** [comment]
I'm poking around the GA overview and not seeing any data sent in. In another tab in browsing the site https://ioos.github.io/notebooks_demos/ to see if my browsing appears in the analytics, still no dice.
image

**Comment by MathewBiddle** [comment]
I wonder if the provider in [_config.yml](https://github.com/ioos/notebooks_demos/blob/master/webpage/_config.yml) should be `google_universal`?

https://github.com/ioos/notebooks_demos/blob/11c14764cb43441e63aa55d52fb1f1aa0c6e717c/webpage/_config.yml#L88

**Comment by ocefpaf** [comment]
Google Analytics changed so much since the last time I used it that I have no idea. I'm OK to just tests things out. However, I do remember that it took a few weeks for the first streams of data to appear. Did you check it again recently? Do we have any data?

**Pull request merged**
