### PR TITLE
Adding data conversion to DwC notebook

### PR DESCRIPTION
**Pull request by MathewBiddle**
Added the source data file to data/. Commented out the bits where we write the resultant data file. Not sure where we'd want to write them, or if we want to? 

Addresses #248

### CODE REVIEW

**Comment by MathewBiddle** [comment]
@ocefpaf, I think the most recent pull request lays out the process a little better and provides links to other resources. If you don't mind taking a look, I'd appreciate any feedback.

**Comment by ocefpaf** [comment]
I'm adding pyworms to conda-forge and then to our env so we can run this. Be back here to review as soon as I finish that...

**Comment by ocefpaf** [comment]
This notebook will need pyworms. I'm adding it in 

> I'm adding pyworms to conda-forge and then to our env so we can run this. Be back here to review as soon as I finish that...

Pending: https://github.com/iobis/pyworms/issues/2

**Comment by MathewBiddle** [comment]
Feedback from Abby:
   1. The text looks good. The only thing you need to change is this line: 
       ```event['eventDate'] = pd.to_datetime(event['date'],format='%m/%d/%Y',utc=True)```
      * You need to remove the `utc=True` part. There is no time information included in the file so we should not add it. Having YYYY-MM-DD is sufficient and is the only information that's recorded. By adding time, you're creating data that's not there and is not accurate.
   1. adjust `writting` to `writing`.
   1.  The way you described what the eventID is doing is missing some information. You say "For this we need to combine all of the measurements or facts that we want to include with the data package into one table using the eventID as a connection to the occurrence records." but it also links to the mof file and not to the occurrences. So for instance this measurement 

0 | St. John_250_1 |   | temperature | http://vocab.nerc.ac.uk/collection/P25/current... | 25.2 | Celsius | http://vocab.nerc.ac.uk/collection/P06/current... | 3 | 2004-07-16 00:00:00+00:00
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

only has an eventID and does not have an occurrenceID so in this instance the eventID is linking the measurement (temperature) to the event but it's not linking to the occurrence.

**Comment by ocefpaf** [comment]
LGTM. Do you want to remove the commended out code cells before we merge?
Also, pyworms is not on conda-forge b/c of https://github.com/iobis/pyworms/issues/2
Hopefully we can solve that one with upstream and package it.

**Comment by MathewBiddle** [comment]
Yeah, I'll uncomment those lines. 

Should we have the output files written to a subdir in `data/` ? Might be nice to have them available for folks to review.

Should I rebase and merge?

**Comment by ocefpaf** [comment]
> Should we have the output files written to a subdir in `data/` ? Might be nice to have them available for folks to review.

That would be nice. Specially for folks who will try to run this locally.

> Should I rebase and merge?

No need. Without pyworms that won't help much.

**Comment by MathewBiddle** [comment]
@ocefpaf, I created a new data structure for these data:
```
data
└───dwc
    ├───processed
    │       MadeUpData_event.csv
    │       MadeUpData_mof.csv
    │       MadeUpData_Occurrence.csv
    │
    └───raw
            MadeUpDataForBiologicalDataTraining.csv
```

If you're good, feel free to merge.

**Comment by ocefpaf** [comment]
> If you're good, feel free to merge.

Do we want this without pyworms? We cannot install it in our envs until https://github.com/iobis/pyworms/issues/2 is solved. Maybe we should ping the author again.

**Comment by MathewBiddle** [comment]
can we PR a license to that repo?

**Comment by MathewBiddle** [comment]
can we push this out without pyworms (I do include a note on how to install via github and pip), and work with them on the license?

**Comment by ocefpaf** [comment]
> can we PR a license to that repo?

We can but that is something the author should do.

> can we push this out without pyworms (I do include a note on how to install via github and pip), and work with them on the license?

We would need to skip it from the CIs, but sure, that is a possibility. However, ideally we should not encourage use of unlicensed code IMO.

**Comment by ocefpaf** [comment]
@MathewBiddle we have pyworms on conda-forge! Are you done with this PR? Should we merge it?

**Comment by MathewBiddle** [comment]
@ocefpaf Wahoo! If you've taken a look and think it's good, then let's merge it!

**Comment by MathewBiddle** [comment]
Actually, I need to remove the git installation note since it's available on conda-forge.

**Comment by MathewBiddle** [comment]
Okay, now it should be good to merge.

**Comment by MathewBiddle** [comment]
@ocefpaf looks like we built the urls to the files incorrectly. The notebook links to https://github.com/master/notebooks_demos/blob/master/notebooks/data/dwc/processed/MadeUpData_Occurrence.csv
when it should be
https://github.com/ioos/notebooks_demos/blob/master/notebooks/data/dwc/processed/MadeUpData_Occurrence.csv

**Pull request merged**
