### PR TITLE
Adding a bagit example. fixes #134

### LINKED ISSUE #134: How to submit data to NCEI using bagit in python
@mbiddle-nodc said he would like to see if we can make a notebook about using bagit (https://github.com/LibraryOfCongress/bagit-python) to create submission packages for NCEI. 

I think this is a great idea!

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jbosch-noaa I can merge this and add more "text" to tell a story later (I am assuming you don't want to do that @kwilcox :wink:).

The example is concise and to the point. I really like this notebook.

Closes #134

**Comment by kwilcox** [comment]
This should pass now, pocean had to be updated to conda-forge

**Comment by rsignell-usgs** [comment]
Okay to merge this?

**Comment by ocefpaf** [comment]
IMO yes. See https://github.com/ioos/notebooks_demos/pull/273#issuecomment-341911504

Ping @jbosch-noaa

**Pull request merged**
