### PR TITLE
IOOS models

### LINKED ISSUE #304: IOOS Model Grids
Opening a issue here so @dpsnowden  and I can track the progress of this specific notebook.

In Issue: https://github.com/ioos/notebooks_demos/issues/284 @ocefpaf  references a [preliminary notebook](http://nbviewer.jupyter.org/gist/ocefpaf/5e5059ee6a73a32105bccf72249a0690)

@ocefpaf  - @dpsnowden requested that you please submit a pull request for this code so he can comment.

### PR DESCRIPTION
**Pull request by ocefpaf**
# Not ready for merging yet

@jbosch-noaa here are the hypothes.is links:

### Grid and model statistics:

http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/ioos_models/notebooks/2018-04-30-grids.ipynb

### Horizontal slices for temperature:

http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/ioos_models/notebooks/2018-04-30-temperature-horizontal.ipynb

### Horizontal slices for salinity:

http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/ioos_models/notebooks/2018-04-30-salinity-horizontal.ipynb

### Horizontal slices for sea surface height:

http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/ioos_models/notebooks/2018-04-30-sea-surface-height-horizontal.ipynb

This notebook only deals with the various models grids at the moment. Once we define all the models we want and how to show the grids we can expand with horizontal and vertical slices of temperature, salinity, etc.

Closes #304, #284 

PS: check the models available on https://eds.ioos.us/

### CODE REVIEW

**Comment by ocefpaf** [comment]
From #284 we need to show

> Simple stats on characteristics of the model (resolution, grid type, vertical levels, time step)

- [ ] resolution: some models have a varying resolution, I'll if we can extract that information from the grid and show use the most coarse cell as the number here
- [X] grid type: Done, `gridgeo` identify `SGRID`, `UGRID`, unknown 1D and 2D
- [ ] vertical levels: should be easy if we use the non-dimension vertical coord to identify that
- [ ] time step: we can get the results time-step, but that may be averaged and not reflect the actual model run time-step.

**Comment by jbosch-noaa** [comment]
@ocefpaf  - Is this read to be looked at yet?

**Comment by ocefpaf** [comment]
> @ocefpaf - Is this read to be looked at yet?

Loading the various grid formats in quite complex but I guess we finally got it working in the latest version, see the hypothes.is link below.

The next issue is to get meaningful information regarding the models from the data available in the servers. The data is lossy we cannot assure that the time/space resolution of the model is the one in the date served (interpolations and other post-processing procedures can hinder that). Also, not all the info we want is present, like `time step` in cell [13].

The next step is to make the graphs prettier and start working on the vertical and horizontal slices.

https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/ioos_models/notebooks/2018-03-28-grids.ipynb

**Comment by jbosch-noaa** [comment]
@ocefpaf  - Sorry I haven't forgotten about this - just super busy.  These notebooks are good but as you said, they can use some polishing (axes labeling, units, markdown narrative etc).  I would polish the first one and get feedback from @dpsnowden  and others.  If one or two models rise to the top of interest then I suggest we dig (dive) deeper. :D

**Comment by ocefpaf** [comment]
@mwengren can you restore my merge rights for this repository too?

**Comment by mwengren** [comment]
Yup, already done @ocefpaf

**Comment by mwengren** [comment]
@ocefpaf Just let me know what other repos you need access to and I'll add you to those teams as well.

**Comment by ocefpaf** [comment]
> @ocefpaf Just let me know what other repos you need access to and I'll add you to those teams as well.

Thanks. I'll send you a list in an e-mail later. On the top of my head I guess that `compliance-checker` would be one of those.

**Comment by mwengren** [comment]
@ocefpaf You've actually been on the compliance-checker team for awhile, so you should still have full write access there.  This is why the org admin approach isn't appropriate, no granularity and unnecessary redundancy.

**Comment by ocefpaf** [comment]
Closing this b/c we decided to do a series of post instead of a single long one.

The first one is ready for review in #321

**Pull request closed without merging**
