### PR TITLE
Travis-CI

### PR DESCRIPTION
**Pull request by ocefpaf**
Test the environment creation, run all notebooks, and output the resulting HTML.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Since system-test I wanted to do that! :tada:

**Comment by rsignell-usgs** [comment]
Nice work!   Fingers crossed for "build passing!"

**Comment by ocefpaf** [comment]
It passed in this PR but it will be flaky b/c many things (catalog down, network issues, library changes) can be at fault. However, this is not a real test where failure means "do not merge." I see this as a guide to help us debug issues quicker.

**Comment by rsignell-usgs** [comment]
got it.

**Pull request merged**
