### PR TITLE
Uses bokeh plots

### PR DESCRIPTION
**Pull request by ocefpaf**
Not ready yet...

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
oops, just committed -- didn't see the "not ready yet".   Should I revert?

**Comment by ocefpaf** [comment]
> Not ready yet...

?

**Comment by ocefpaf** [comment]
Yes please!

**Comment by ocefpaf** [comment]
Since we cannot re-open this PR I will send a new one. (Only when it is ready this time.)

**Pull request merged**
