### PR TITLE
Add binder badge...

### PR DESCRIPTION
**Pull request by ocefpaf**
... and update README title.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@ocefpaf  Awesome!  Thanks!

**Comment by ocefpaf** [comment]
Putting this together gave me so many new ideas to improve these libraries...

**Comment by rsignell-usgs** [comment]
Great!   Now all you need is time, right?  :smiley_cat:

**Comment by rsignell-usgs** [comment]
Actually, it would be great if you could make notes on these new ideas.
Would that be possible?

**Comment by ocefpaf** [comment]
I have some local notes for now. I will create issues accordingly.

**Pull request merged**
