### PR TITLE
@rsignell-usgs suggestions

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs I implemented two of your requests:

- no more served external HTML, I found a solution to bundle the generated HTML and by pass the `Jupyter` notebook `__repr__` limitation;
- added a hover `tooltip` to the `bokeh` plots.

The `tooltip` shows the variable name and data y-value. I could not get bokeh date formatting to work to show the x-value.

https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/rsignell-usgs_suggestions/notebooks/2017-09-09-hurricane_irma.ipynb

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
I would still prefer to remove the hardwired aspects of cell [16], just picking a random station.   
Or just delete it.   
Or move it to the end.

**Comment by ocefpaf** [comment]
> I would still prefer to remove the hardwired aspects of cell [16], just picking a random station.
Or just delete it.
Or move it to the end.

The original idea was a notebook focused on Irma that is why I added that close inspection to one of the stations. I don't really have a strong opinion.

What do you think @jbosch-noaa?

**Comment by jbosch-noaa** [comment]
I think we should leave it.  I am already advertising this notebook as showcasing Irma data.  If we can add more Irma data the better.

**Comment by rsignell-usgs** [comment]
That's fine.  I can always delete it when I'm showing it.    My pitch will be that it works for Irma, but the real power is that you can change the number and it will work for any storm, which is very cool (we are now interested in Jose!)

**Comment by ocefpaf** [comment]
> That's fine. I can always delete it when I'm showing it.

I deleted it from my own [1] non-blog version.
B/c  this one here is focused on Irma I guess it is better to keep it.

> My pitch will be that it works for Irma, but the real power is that you can change the number and it will work for any storm, which is very cool (we are now interested in Jose!)

BTW, I just got a message from a friend in Cuba who is running it for `al142017`.
I guess that José is New England's problem now.

[1] https://github.com/ocefpaf/python_hurricane_gis_map

**Pull request merged**
