### PR TITLE
Add nbdime

### PR DESCRIPTION
**Pull request by ocefpaf**
`nbdime` will change how we do diff and merges in notebooks. See https://nbdime.readthedocs.io/en/latest/

(I also fixed the `IOOS2` env a little bit.)

### CODE REVIEW

**Comment by lukecampbell** [comment]
That's sweet 👍

**Comment by ocefpaf** [comment]
@lukecampbell install, issue the commands,

```shell
git-nbdiffdriver config --enable --global
git-nbmergedriver config --enable --global
```

and enjoy :wink:

**Comment by lukecampbell** [comment]
I can't remember if it's default or not, but commands that start with `git-` can sometimes be executed using git:

```
git nbdiffdriver config --enable --global
```

See if that works for you?

**Comment by ocefpaf** [comment]
@ioos/clients those commands I sent you only adds:

```
[diff "jupyternotebook"]
    command = git-nbdiffdriver diff
[merge "jupyternotebook"]
    driver = git-nbmergedriver merge %O %A %B %L %P
    name = jupyter notebook merge driver
```

to your gitconfig, so you can later do `git diff a_notebook.ipynb` ans see something meaningful instead of an ugly JSON diff..

**Pull request merged**
