### PR TITLE
try to build an env with latest robis

### PR DESCRIPTION
**Pull request by ocefpaf**
Also remove rise from the env.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@MathewBiddle the env builds correctly and I get:

```
> conda list obis
# packages in environment at /home/filipe/miniconda3/envs/IOOS:
#
# Name                    Version                   Build  Channel
r-robis                   2.3.9             r40h6115d3f_0    conda-forge
```

Note that is the latest version on CRAN, which conda-forge uses to create the package. However, there are some GitHub releases upstream, not sure if that is what you need. See https://github.com/iobis/robis/releases

If so, I need to package from GitHub instead of CRAN.

**Comment by MathewBiddle** [comment]
@ocefpaf, that's the version I was hoping to have. Looks like I need to rebuild the environment. Apparently, when I built it, version 2.1.8 was the most recent?
```
(IOOS) C:\>conda list obis
# packages in environment at C:\Users\Mathew.Biddle\programs\Anaconda3\envs\IOOS:
#
# Name                    Version                   Build  Channel
r-robis                   2.1.8             r35h6115d3f_1    conda-forge
```
I'll remove the environment and rebuild it. That should resolve the issue.

**Comment by MathewBiddle** [comment]
@ocefpaf, somethings up. I just removed the IOOS env, then reinstalled from the file [environment-python_and_r.yml](https://raw.githubusercontent.com/ioos/notebooks_demos/master/environment-python_and_r.yml) which used to be linked at https://ioos.github.io/notebooks_demos/other_resources/. Now the link is broken.  

Luckily, I had a copy of the file locally still, so I was able to build the env using that (downloaded back in Sept). 

However, now in the newly created IOOS env, I have the older version of r-obis:
```
(IOOS) C:\Users\Mathew.Biddle\Downloads>conda list obis
# packages in environment at C:\Users\Mathew.Biddle\programs\Anaconda3\envs\IOOS:
#
# Name                    Version                   Build  Channel
r-robis                   2.1.8             r35h6115d3f_1    conda-forge
```

**Comment by MathewBiddle** [comment]
Ahh, didn't realize I needed to grab the new yml file from https://github.com/ioos/notebooks_demos/blob/master/.binder/environment-python_and_r.yml (which should be linked on the webpage). Trying that file now.

**Comment by MathewBiddle** [comment]
All is good now:
```
(IOOS) C:\Users\Mathew.Biddle\Downloads>conda list obis
# packages in environment at C:\Users\Mathew.Biddle\programs\Anaconda3\envs\IOOS:
#
# Name                    Version                   Build  Channel
r-robis                   2.3.9             r40h6115d3f_0    conda-forge
```

**Comment by ocefpaf** [comment]
OK. Let's merge this one then to ensure we'll get the latest version.
The link to the env file was fixed in #375 will be live as soon as we publish the new page.

**Pull request merged**
