### PR TITLE
Closes #135

### LINKED ISSUE #135: Link the notebook repo file to each post
@ocefpaf  - 
Feedback from @dpsnowden that I think is a great suggestion.  We should put a link to the notebook .ipynb file on the repo at the bottom of the published notebook on the blog so folks can download the  file and run it themselves.

This would of course mean editing the already published notebooks (all 3 of them) and making it a habit to do so with all future notebooks. :)

### PR DESCRIPTION
**Pull request by ocefpaf**
@jbosch-noaa check the last cell in http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/bafb9f6d33bfcf75349bcb7192918ddc32827dca/notebooks/2016-10-12-fetching_data.ipynb to see how it will look like.

PS: Note that, since the notebook file is valid `JSON`, most browsers will try to open it instead of downloading. I did not add a "Right click and save as..." instruction because that is pretty common these days. But we can  add that if you think it is important.

### CODE REVIEW

**Comment by jbosch-noaa** [comment]
Actually that might be a good idea for folks less informed than us. :)

**Comment by ocefpaf** [comment]
Is this OK?

---

Right click and choose Save link as... to [download](https://raw.githubusercontent.com/ioos/notebooks_demos/master/notebooks/2016-10-12-fetching_data.ipynb) this notebook, or see a static view [here](http://nbviewer.ipython.org/urls/raw.githubusercontent.com/ioos/notebooks_demos/master/notebooks/2016-10-12-fetching_data.ipynb).

---

**Comment by ocefpaf** [comment]
I did not put that in yet :smile: 

I was waiting for you :+1: first. No problem. I will re-send this PR.

PS: It is not your fault. Unfortunately `notebooks` diffs are terrible on GitHub and you had no way of knowing!

**Comment by jbosch-noaa** [comment]
sorry .. i was trigger happy : P

**Comment by ocefpaf** [comment]
No problem. See #141

**Pull request merged**
