### PR TITLE
Draft for SCCOOS HABs

### PR DESCRIPTION
**Pull request by ocefpaf**
Initial work to address #365

### CODE REVIEW

**Comment by MathewBiddle** [comment]
For some reason, I can't get the leaflet maps to display in Jupyter. When I run the code in RStudio, it all works fine. But, Jupyter has some hiccup with the leaflet maps...

**Comment by ocefpaf** [comment]
> For some reason, I can't get the leaflet maps to display in Jupyter. When I run the code in RStudio, it all works fine. But, Jupyter has some hiccup with the leaflet maps...

I believe that is known to not work properly. Hopefully we'll get RStudio up and running on binder soon. (The rendered version in the site will still use jupyter but I guess there are a few workarounds to get it to display in the HTML form.)

**Comment by MathewBiddle** [comment]
Still a draft. Just trying to figure out how to gather the occurrence and measurement or fact observations.

**Comment by ocefpaf** [comment]
BTW, I made a few modifications on the CI system and the page publication. All should be working on GitHub pages now. Can you try to rebase so we can see the tests run?

**Comment by ocefpaf** [comment]
@MathewBiddle I rebased this against latest `main` so the tests can run properly. You may need to do a `git pull` before commiting new code on this PR.

**Comment by MathewBiddle** [comment]
I have the map doing, somewhat, what I want (still a ways to go):
image

It's very clunky by saving the time-series images to a file, then displaying them in the popup. Similarly for displaying the map in Jupyter. Can we make the map bigger in the notebook or find a way around saving a bunch of local files?

TODO: 
- [ ] only create time-series mof plots for mofs that were observed at that location. 
- [ ] time-series plots should have two y axis, the mof and organismQuantity. To see how that mof might have impacted quantity.
- [ ] make a cleaner time-series plot.

**Comment by MathewBiddle** [comment]
look at plotly::ggplotly for interactivity: htmlwidgets.org or maybe dygraphs for time series plots, or maybe https://cran.r-project.org/web/packages/trelliscopejs/vignettes/trelliscopejs.html

**Pull request closed without merging**
