### PR TITLE
Extend time in gts notebook

### PR DESCRIPTION
**Pull request by MathewBiddle**
I've made the time constraint more dynamic. Since the `now` functionality [doesn't work with erddapy](https://github.com/ioos/erddapy/issues/164), I've done it using timedelta.

### CODE REVIEW

**Comment by mwengren** [comment]
Looks like a good workaround for the 'now-timeduration' limitation in erddapy @MathewBiddle.  Hopefully we can support more of ERDDAP server-side functions in future erddapy versions.

**Comment by MathewBiddle** [comment]
@kbailey-noaa mentioned that making it more interactive might be useful. I've attempted to add in widgets for picking start and end dates. I'm wondering if we could add voila to this and give the user the time duration selector, then all the graphs and statistics could appear at the bottom of the page? Might be more useful that way instead of a 'data demo' notebook.

**Comment by MathewBiddle** [comment]
FYI, it looks like this notebook (a previous iteration of it) got pushed to the notebook site: https://ioos.github.io/notebooks_demos/notebooks/2020-10-10-GTS/

Not sure if we wanted to merge any of this additional work in? BTW the map isn't displayed at the bottom.

**Comment by ocefpaf** [comment]
> FYI, it looks like this notebook (a previous iteration of it) got pushed to the notebook site: https://ioos.github.io/notebooks_demos/notebooks/2020-10-10-GTS/

I fixed the auto publication, so now all the merged PRs will be on the site. I can rebase this one later today and we can publish a newer version.

> Not sure if we wanted to merge any of this additional work in? BTW the map isn't displayed at the bottom.

I'm in touch with ipyleaflet folks to fix that but I'm inclined to switch back to folium b/c of that :-/

**Comment by MathewBiddle** [comment]
> I fixed the auto publication, so now all the merged PRs will be on the site. I can rebase this one later today and we can publish a newer version.

Awesome! No need to rebase if we aren't ready to push this PR out. I don't recall where we left this at.

>I'm in touch with ipyleaflet folks to fix that but I'm inclined to switch back to folium b/c of that :-/

bummer

**Comment by MathewBiddle** [comment]
@ocefpaf, the most recent PR of this notebook uses widgets to get the `start date` and `end date` to query the ERDDAP server. I assume this will not be functional in the Data Demo Center. I think we should leave the notebook that is [currently published](https://ioos.github.io/notebooks_demos/notebooks/2020-10-10-GTS/) alone. 

We should work up something else, maybe more interactive for Kathy. I've tested the [most recent PR on google colab](https://colab.research.google.com/github/MathewBiddle/notebooks_demos/blob/extend_time_in_GTS_notebook/notebooks/2020-10-10-GTS.ipynb) and that might a good solution for @kbailey-noaa. You just need to add a cell at the beginning to install some required packages, but after that you can dig into the data however you want to.
```
!pip install ipywidgets
!pip install erddapy
!pip install pandas
!pip install ipyleaflet
```

**Comment by ocefpaf** [comment]
> @ocefpaf, the most recent PR of this notebook uses widgets to get the `start date` and `end date` to query the ERDDAP server. I assume this will not be functional in the Data Demo Center. I think we should leave the notebook that is [currently published](https://ioos.github.io/notebooks_demos/notebooks/2020-10-10-GTS/) alone.

Without a live kernel de widgets cannot get updated values from a server but if all the results are in the current state we can save the widget state and publish. Do you want to try that?

> We should work up something else, maybe more interactive for Kathy. I've tested the [most recent PR on google colab](https://colab.research.google.com/github/MathewBiddle/notebooks_demos/blob/extend_time_in_GTS_notebook/notebooks/2020-10-10-GTS.ipynb) and that might a good solution for @kbailey-noaa. You just need to add a cell at the beginning to install some required packages, but after that you can dig into the data however you want to.
> 
> ```
> !pip install ipywidgets
> !pip install erddapy
> !pip install pandas
> !pip install ipyleaflet
> ```

Yeah, colab has a fixed set of packages. Nice for testing but not really great for development.

**Comment by ocefpaf** [comment]
@MathewBiddle I'm sorry but I caused from conflicts here. Fixing conflicts in Jupyter notebooks is quite annoying. Do you mind saving the file you have on disk and re-submitting this PR?

**Comment by MathewBiddle** [comment]
I've got the GTS notebook saved locally. Not sure how to 
>re-submitting this PR

**Comment by ocefpaf** [comment]
> I've got the GTS notebook saved locally. Not sure how to
> 
> > re-submitting this PR

Sorry. Autocomplete and cellphone did not help. I meant a new PR with the saved notebook.

**Comment by MathewBiddle** [comment]
See #398

**Pull request closed without merging**
