### PR TITLE
add bagit text

### PR DESCRIPTION
**Pull request by ocefpaf**
@jbosch-noaa this is @kwilcox's notebook on bagit with some text to help the reader understands what is going on in the code cells.

Here is the `hypothes.is` link for review: https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/bagit_text/notebooks/2017-11-01-Creating-Archives-Using-Bagit.ipynb

### CODE REVIEW

**Comment by jbosch-noaa** [comment]
This notebook looks great!  Thanks to both of you (@kwilcox, @ocefpaf ) for putting it together.  After reading the notebook I finally understand what Bagit does.  :)

**Comment by ocefpaf** [comment]
There are some missing details about the meaning of the hashes, etc. But I did not want to get into that b/c I don't think most of the user would be interested.

**Comment by jbosch-noaa** [comment]
That's fine about the hashes. I just think one statement at the top regarding what folks would use BagIt for in the IOOS context would be helpful.

**Comment by ocefpaf** [comment]
> I just think one statement at the top regarding what folks would use BagIt for in the IOOS context would be helpful.

I actually never used it and I am not sure how `BagIt` is used in the IOOS context... But how about:

     `BagIt` is used to ensure digital preservation of oceanographic datasets within IOOS and
     its regional associations.

**Comment by jbosch-noaa** [comment]
That sounds good.  Just add that and then we can merge it.

**Comment by kwilcox** [comment]
`BagIt` packages can be used to facilitate data sharing with federal archive centers - thus ensuring digital preservation of oceanographic datasets within IOOS and its regional associations. NOAA NCEI supports reading from a Web Accessible Folder (WAF) containing bagit archives. For an example please see: http://ncei.axiomdatascience.com/cencoos/

**Comment by ocefpaf** [comment]
I think @kwilcox's version is better :smile:

**Comment by jbosch-noaa** [comment]
I agree.  Thanks @kwilcox !

**Comment by ocefpaf** [comment]
> I agree. Thanks @kwilcox !

Added that. This is good to go @jbosch-noaa.

**Comment by ocefpaf** [comment]
Fixed that in #278 but I I'll try to fix the gallery later so we can use links in the titles without that problem.

**Comment by jbosch-noaa** [comment]
@ocefpaf -I Got this feedback from @emiliom off the ioos_tech email list and I think we should make these edits:

Bob's clarification about BagIt is an important one. I'd like to suggest a couple of small tweaks to the notebook preamble text to avoid confusion:

- Change the "BagIt" link at the start of the paragraph to point to https://en.wikipedia.org/wiki/BagIt instead of the python bagit package
- In the second paragraph, make the phrase "python interface" into a link that points to the python bagit package, http://libraryofcongress.github.io/bagit-python

Cheers,
-Emilio

**Pull request merged**
