### PR TITLE
test miniconda rc with 4.7

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @msarahan.

### CODE REVIEW

**Comment by msarahan** [comment]
Waiting with bated breath. Come on green....

**Comment by ocefpaf** [comment]
The failure is unrelated, so I guess it is working.
I need to split the actual env creation as its own test and then the notebooks into another.

**Comment by ocefpaf** [comment]
@msarahan all rcs of miniconda are building the IOOS environment without a problem. (I also send the links to some people to test. No one report problems.)

**Comment by msarahan** [comment]
Thanks for the testing!

**Comment by ocefpaf** [comment]
BTW, if you set up a "nightly" URL for miniconda we could use that to continuously test it here.

**Comment by msarahan** [comment]
Will do. We have them in ci, but we need to publish them.

**Pull request merged**
