### PR TITLE
ssh skill score notebook

### PR DESCRIPTION
**Pull request by ocefpaf**
~~# This notebook is not read for review yet!~~

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jbosch-noaa this is ready for the first round of reviews now:

https://via.hypothes.is/http://nbviewer.jupyter.org/github/ocefpaf/notebooks_demos/blob/ssh_skill_score/notebooks/2018-03-15-ssh-skillscore.ipynb

@rsignell-usgs suggested the dates from `2018-2-28 00:00:00` to `2018-3-5 00:00:00` b/c of the strongs winds observed on March 4th, but I don't think we can see interesting sea level changes there (but I may be missing them).

**Comment by jbosch-noaa** [comment]
@ocefpaf - Wow! This is a really good notebook.  I hope folks find it useful. : )
I reviewed the notebook and have some edits towards the bottom.

**Comment by ocefpaf** [comment]
> I reviewed the notebook and have some edits towards the bottom.

Done! Ready for another round of reviews.

**Comment by jbosch-noaa** [comment]
Looks good! I will merge the pull request but it currently indicates the checks have failed...

**Comment by ocefpaf** [comment]
> Looks good! I will merge the pull request but it currently indicates the checks have failed...

On Windows we are missing `obistools` as a dependency for the *obis* notebook. On Linux we are facing time-outs b/c our notebooks are quite demanding of the network.

I'll try to workaround those to make the tests more meaningful, but it is safe to merge.

**Pull request merged**
